name: hirome_rental_shop_web
description: ひろめ市場 食器レンタルシステム - 店舗専用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  modal_bottom_sheet: ^2.1.2
  top_snackbar_flutter: ^3.1.0
  device_info_plus: ^9.0.2
  calendar_date_picker2: ^0.5.2
  month_picker_dialog: ^2.0.2
  csv: ^5.0.2
  http: ^1.1.0
  url_launcher: ^6.1.14
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_messaging: ^14.6.5

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf